version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=safa2004*
      - DB_NAME=Auth_app
    volumes:
      - .:/app
    networks:
      - appnet

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: safa2004*
      MYSQL_DATABASE: Auth_app
    ports:
      - "3306:3306"
    networks:
      - appnet
    volumes:
      - dbdata:/var/lib/mysql

networks:
  appnet:

volumes:
  dbdata:
